# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
---
name: qtile-silver

description: This is my custom image for using QTile alongside GNOME.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - alacritty
        - dbus-daemon
        - distrobox
        - direnv
        - screen
        - tesseract
        - tesseract-langpack-eng
        - tesseract-langpack-deu
        - tmux
        - vim
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - from-file: common/qtile.yml
  - from-file: common/flatpak.yml
  - from-file: common/gnome.yml

  - type: signing
