---
name: qtile-silver

description: This is my custom image for using QTile alongside GNOME.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - alacritty
        - nautilus
        - sushi
    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency
        - gnome-software
        - gnome-software-rpm-ostree

  - from-file: common/qtile-modules.yml
  - from-file: common/flatpak-modules.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
